### ISSUE TITLE
关于导出数据

### ISSUE THREAD

**Issue by immarktube** [andyczy/czy-nexus-commons-utils#1]
你好，在README-3.2.md里的导出数据里  最后的listArray我没看到你在哪定义的，datalists也没看到你是在哪里往里加参数的

**Comment by immarktube** [comment]
并且，导出至D盘时打开会报文件已损坏的错。

**Comment by andyczy** [comment]
问题1：
看看文档
https://github.com/andyczy/czy-nexus-commons-utils/blob/master/README-3.2.md

问题2：用wps打开试试


649954910@qq.com
 
发件人： 阳阳
发送时间： 2019-01-02 15:50
收件人： andyczy/czy-nexus-commons-utils
抄送： Subscribed
主题： Re: [andyczy/czy-nexus-commons-utils] 关于导出数据 (#1)
并且，导出至D盘时打开会报文件已损坏的错。
